"use strict";

/**
 * Heuristic topic assignment for A1 vocabulary.
 * Reads data/word/a11.json and data/word/a12.json, removes `category`,
 * adds `topics` array based on German/EN/FA text and example, and rewrites the files.
 *
 * Topics:
 * - Begrüßung & Höflichkeit
 * - Persönliche Daten & Vorstellen
 * - Familie & Freunde
 * - Zahlen, Uhrzeit & Datum
 * - Wohnen & Haushalt
 * - Essen & Trinken
 * - Einkaufen & Geld
 * - Stadt & Orientierung
 * - Reisen & Verkehr
 * - Körper & Gesundheit
 * - Schule, Kurs & Lernen
 * - Arbeit & Beruf (einfach)
 * - Hobbys & Freizeit
 * - Wetter & Jahreszeiten
 * - Alltag & Routinen
 * - Kommunikation & Reaktion
 * - Grammatik & Funktionswörter
 */

const fs = require("fs");
const path = require("path");

const topicList = [
  "Begrüßung & Höflichkeit",
  "Persönliche Daten & Vorstellen",
  "Familie & Freunde",
  "Zahlen, Uhrzeit & Datum",
  "Wohnen & Haushalt",
  "Essen & Trinken",
  "Einkaufen & Geld",
  "Stadt & Orientierung",
  "Reisen & Verkehr",
  "Körper & Gesundheit",
  "Schule, Kurs & Lernen",
  "Arbeit & Beruf (einfach)",
  "Hobbys & Freizeit",
  "Wetter & Jahreszeiten",
  "Alltag & Routinen",
  "Kommunikation & Reaktion",
  "Grammatik & Funktionswörter",
];

const keywordMap = {
  "Begrüßung & Höflichkeit": [
    "hallo",
    "hi",
    "guten morgen",
    "guten tag",
    "guten abend",
    "tschüss",
    "servus",
    "grüß dich",
    "bitte",
    "danke",
    "dank",
    "entschuldigung",
    "goodbye",
    "bye",
    "hello",
    "thanks",
    "thank you",
    "sorry",
    "سلام",
    "خداحافظ",
    "صبح بخیر",
    "لطفاً",
    "ممنون",
    "متشکرم",
    "ببخشید",
  ],
  "Persönliche Daten & Vorstellen": [
    "name",
    "heißen",
    "komme aus",
    "kommen aus",
    "wohnen",
    "adresse",
    "straße",
    "ort",
    "stadt",
    "land",
    "alter",
    "jahre alt",
    "verheiratet",
    "ledig",
    "sprache",
    "geburtsdatum",
    "name",
    "age",
    "years old",
    "from",
    "country",
    "city",
    "address",
    "nationality",
    "language",
    "نام",
    "سن",
    "کشور",
    "شهر",
    "ملیت",
    "زبان",
    "آدرس",
  ],
  "Familie & Freunde": [
    "mutter",
    "vater",
    "eltern",
    "bruder",
    "schwester",
    "kind",
    "kinder",
    "sohn",
    "tochter",
    "onkel",
    "tante",
    "oma",
    "opa",
    "freund",
    "freundin",
    "kollege",
    "family",
    "mother",
    "father",
    "brother",
    "sister",
    "friend",
    "colleague",
    "مادر",
    "پدر",
    "برادر",
    "خواهر",
    "دوست",
    "همکار",
    "خانواده",
  ],
  "Zahlen, Uhrzeit & Datum": [
    "eins",
    "zwei",
    "drei",
    "vier",
    "fünf",
    "sechs",
    "sieben",
    "acht",
    "neun",
    "zehn",
    "elf",
    "zwölf",
    "zwanzig",
    "hundert",
    "tausend",
    "uhr",
    "stunde",
    "minute",
    "sekunde",
    "montag",
    "dienstag",
    "mittwoch",
    "donnerstag",
    "freitag",
    "samstag",
    "sonntag",
    "januar",
    "februar",
    "märz",
    "april",
    "mai",
    "juni",
    "juli",
    "august",
    "september",
    "oktober",
    "november",
    "dezember",
    "heute",
    "morgen",
    "gestern",
    "datum",
    "number",
    "date",
    "time",
    "hour",
    "minute",
    "second",
    "day",
    "month",
    "year",
    "عدد",
    "تاریخ",
    "روز",
    "ماه",
    "سال",
    "ساعت",
    "دقیقه",
  ],
  "Wohnen & Haushalt": [
    "wohnung",
    "haus",
    "zimmer",
    "küche",
    "bad",
    "bett",
    "tisch",
    "stuhl",
    "schrank",
    "fenster",
    "tür",
    "miete",
    "vermieter",
    "nachbar",
    "putzen",
    "aufräumen",
    "home",
    "flat",
    "apartment",
    "room",
    "kitchen",
    "bathroom",
    "rent",
    "landlord",
    "neighbor",
    "خانه",
    "آپارتمان",
    "اتاق",
    "آشپزخانه",
    "حمام",
    "میز",
    "صندلی",
  ],
  "Essen & Trinken": [
    "essen",
    "trinken",
    "frühstück",
    "mittagessen",
    "abendessen",
    "restaurant",
    "café",
    "brot",
    "wasser",
    "kaffee",
    "tee",
    "milch",
    "zucker",
    "salz",
    "apfel",
    "food",
    "meal",
    "eat",
    "drink",
    "breakfast",
    "lunch",
    "dinner",
    "coffee",
    "tea",
    "غذا",
    "خوردن",
    "نوشیدن",
    "صبحانه",
    "ناهار",
    "شام",
    "رستوران",
    "میوه",
    "نوشیدنی",
  ],
  "Einkaufen & Geld": [
    "kaufen",
    "verkaufen",
    "einkaufen",
    "supermarkt",
    "markt",
    "rechnung",
    "preis",
    "euro",
    "geld",
    "bar",
    "karte",
    "rabatt",
    "billig",
    "teuer",
    "buy",
    "sell",
    "shopping",
    "price",
    "money",
    "invoice",
    "cheap",
    "expensive",
    "cash",
    "card",
    "خرید",
    "فروش",
    "قیمت",
    "پول",
    "صورتحساب",
    "ارزان",
    "گران",
  ],
  "Stadt & Orientierung": [
    "stadt",
    "bahnhof",
    "straße",
    "platz",
    "park",
    "kirche",
    "bank",
    "post",
    "links",
    "rechts",
    "geradeaus",
    "abbiegen",
    "weg",
    "plan",
    "karte",
    "city",
    "street",
    "park",
    "bank",
    "post office",
    "left",
    "right",
    "straight",
    "way",
    "map",
    "شهر",
    "خیابان",
    "پارک",
    "بانک",
    "راست",
    "چپ",
    "مسیر",
  ],
  "Reisen & Verkehr": [
    "reise",
    "fahren",
    "auto",
    "bus",
    "bahn",
    "zug",
    "flugzeug",
    "ticket",
    "bahnhof",
    "haltestelle",
    "flughafen",
    "travel",
    "trip",
    "car",
    "bus",
    "train",
    "ticket",
    "airport",
    "سفر",
    "ماشین",
    "اتوبوس",
    "قطار",
    "بلیط",
    "فرودگاه",
  ],
  "Körper & Gesundheit": [
    "körper",
    "kopf",
    "hand",
    "bein",
    "schmerz",
    "krank",
    "gesund",
    "arzt",
    "termin",
    "tablette",
    "body",
    "head",
    "hand",
    "leg",
    "health",
    "sick",
    "doctor",
    "medicine",
    "بدن",
    "سر",
    "دست",
    "پا",
    "درد",
    "سلامتی",
    "بیمار",
    "دکتر",
  ],
  "Schule, Kurs & Lernen": [
    "schule",
    "lehrer",
    "schüler",
    "kurs",
    "deutschkurs",
    "hausaufgabe",
    "lernen",
    "prüfen",
    "school",
    "course",
    "class",
    "teacher",
    "student",
    "homework",
    "learn",
    "مدرسه",
    "کلاس",
    "دبیر",
    "درس",
    "آموزش",
  ],
  "Arbeit & Beruf (einfach)": [
    "arbeit",
    "job",
    "beruf",
    "kollege",
    "chef",
    "firma",
    "büro",
    "work",
    "job",
    "profession",
    "office",
    "boss",
    "company",
    "کار",
    "شغل",
    "محل کار",
    "رئیس",
    "شرکت",
  ],
  "Hobbys & Freizeit": [
    "hobby",
    "freizeit",
    "lesen",
    "musik",
    "sport",
    "fußball",
    "kino",
    "treffen",
    "spazieren",
    "hobby",
    "free time",
    "sport",
    "football",
    "cinema",
    "سرگرمی",
    "تفریح",
    "ورزش",
    "کتاب",
    "فیلم",
  ],
  "Wetter & Jahreszeiten": [
    "wetter",
    "sonne",
    "regen",
    "schnee",
    "warm",
    "kalt",
    "sommer",
    "winter",
    "frühling",
    "herbst",
    "weather",
    "sunny",
    "rain",
    "snow",
    "warm",
    "cold",
    "season",
    "هوا",
    "آفتابی",
    "باران",
    "برف",
    "گرم",
    "سرد",
    "بهار",
    "تابستان",
    "پاییز",
    "زمستان",
  ],
  "Alltag & Routinen": [
    "jeden tag",
    "immer",
    "oft",
    "manchmal",
    "stehen auf",
    "frühstücken",
    "arbeiten",
    "nach hause",
    "fernsehen",
    "kochen",
    "putzen",
    "daily",
    "every day",
    "routine",
    "always",
    "often",
    "sometimes",
    "روتین",
    "هر روز",
    "روزانه",
  ],
  "Kommunikation & Reaktion": [
    "ja",
    "nein",
    "vielleicht",
    "genau",
    "okay",
    "ok",
    "klar",
    "super",
    "schade",
    "wirklich",
    "natürlich",
    "yes",
    "no",
    "maybe",
    "sure",
    "of course",
    "really",
    "بله",
    "نه",
    "شاید",
    "باشه",
    "حتماً",
    "واقعاً",
  ],
  "Grammatik & Funktionswörter": [
    "der",
    "die",
    "das",
    "ein",
    "eine",
    "ich",
    "du",
    "er",
    "sie",
    "es",
    "wir",
    "ihr",
    "sie",
    "sie",
    "mich",
    "dich",
    "ihn",
    "sie",
    "uns",
    "euch",
    "in",
    "auf",
    "unter",
    "über",
    "bei",
    "mit",
    "ohne",
    "für",
    "von",
    "zu",
    "und",
    "oder",
    "aber",
    "denn",
    "weil",
    "dass",
    "wenn",
    "auch",
    "nur",
    "schon",
    "noch",
    "I ",
    "you",
    "he",
    "she",
    "we",
    "they",
    "and",
    "or",
    "but",
    "in",
    "on",
    "with",
    "because",
    "من",
    "تو",
    "او",
    "ما",
    "شما",
    "آنها",
    "در",
    "روی",
    "ولی",
    "یا",
    "که",
    "هم",
  ],
};

const fallbackTopic = "Grammatik & Funktionswörter";

function normalize(str) {
  return (str || "")
    .toString()
    .toLowerCase()
    .replace(/[.,;:!?()"'`«»،]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function containsKeyword(text, keyword) {
  if (!text) return false;
  return text.includes(keyword);
}

function assignTopics(entry) {
  const texts = [entry.word, entry.translation_en, entry.translation_fa, entry.example]
    .map(normalize)
    .filter(Boolean)
    .join(" ");

  const matched = [];
  for (const topic of topicList) {
    const keys = keywordMap[topic] || [];
    if (keys.some((kw) => containsKeyword(texts, normalize(kw)))) {
      matched.push(topic);
    }
  }

  if (matched.length === 0) {
    matched.push(fallbackTopic);
  }

  return Array.from(new Set(matched)).slice(0, 3);
}

function processFile(filePath) {
  const raw = fs.readFileSync(filePath, "utf8");
  const data = JSON.parse(raw);
  const updated = data.map((item) => {
    if (!/^a1/i.test(item.level)) {
      return item;
    }
    const topics = assignTopics(item);
    const { category, ...rest } = item;
    return { ...rest, topics };
  });
  fs.writeFileSync(filePath, JSON.stringify(updated, null, 2), "utf8");
  console.log(`Updated ${filePath} (${updated.length} entries)`);
}

const files = ["data/word/a11.json", "data/word/a12.json"].map((f) => path.join(process.cwd(), f));
files.forEach(processFile);
